// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7iWdBv9--uV9OAgGBkLcnQQNtya6DhCk',
    appId: '1:183300561393:web:767f1090e5bd7ab76bcc50',
    messagingSenderId: '183300561393',
    projectId: 'chat-app-8e2db',
    authDomain: 'chat-app-8e2db.firebaseapp.com',
    storageBucket: 'chat-app-8e2db.appspot.com',
    measurementId: 'G-RK4PCGHR0J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5VRotvF7SE0nNF6pB1s4BeckNMKsTTzE',
    appId: '1:183300561393:android:72c81f8d9eba08ec6bcc50',
    messagingSenderId: '183300561393',
    projectId: 'chat-app-8e2db',
    storageBucket: 'chat-app-8e2db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDElCNk8FA0BDl-YQCk-BBhGCCEl1tifDA',
    appId: '1:183300561393:ios:bc72dc0f5eff961f6bcc50',
    messagingSenderId: '183300561393',
    projectId: 'chat-app-8e2db',
    storageBucket: 'chat-app-8e2db.appspot.com',
    iosClientId: '183300561393-kq6ntnake07v5v7mfpkcv93ckmtoau31.apps.googleusercontent.com',
    iosBundleId: 'com.example.scholarChat',
  );
}
